config:
  resourceFiltersIncludeNamespaces:
    - 'argocd'
    - 'gke-gmp-system'
    - 'gke-managed-system'
    - 'gke-managed-cim'

# Features configuration
features:
  backgroundScan:
    enabled: true
    skipResourceFilters: false

admissionController:
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
  container:
    resources:
      # -- Pod resource limits
      limits:
        memory: 384Mi
        ephemeral-storage: "1Gi"
      # -- Pod resource requests
      requests:
        cpu: 100m
        memory: 128Mi
        ephemeral-storage: "1Gi"
  metricsService:
    create: false

# Background controller configuration
backgroundController:
  enabled: true
  replicas: 3
  resources:
    # -- Pod resource limits
    limits:
      memory: 128Mi
      ephemeral-storage: "1Gi"
    # -- Pod resource requests
    requests:
      cpu: 100m
      memory: 64Mi
      ephemeral-storage: "1Gi"
  metricsService:
    create: false

# Cleanup controller configuration
cleanupController:
  enabled: true
  replicas: 3
  resources:
    # -- Pod resource limits
    limits:
      memory: 128Mi
      ephemeral-storage: "1Gi"
    # -- Pod resource requests
    requests:
      cpu: 100m
      memory: 64Mi
      ephemeral-storage: "1Gi"
  metricsService:
    create: false

reportsController:
  enabled: true
  replicas: 3
  rbac:
    clusterRole:
      # -- Extra resource permissions to add in the cluster role
      extraResources:
        - apiGroups:
            - ''
          resources:
            - nodes
          verbs:
            - get
            - list
  resources:
    # -- Pod resource limits
    limits:
      memory: 128Mi
      ephemeral-storage: "1Gi"
    # -- Pod resource requests
    requests:
      cpu: 100m
      memory: 64Mi
      ephemeral-storage: "1Gi"
  metricsService:
    create: false
