apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: platform
spec:
  # Project description
  description: Platform for applications

  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - '*'

  sourceNamespaces:
    - platform

  # Only permit applications to deploy to the argocd namespace in the same cluster
  destinations:
    - namespace: platform
      server: https://kubernetes.default.svc
    - namespace: kyverno
      server: https://kubernetes.default.svc

  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  roles:
    - name: platform-admin
      description: Admin role for platform project
      policies:
        - p, proj:platform:platform-admin, applications, *, platform/*, allow
      groups:
        - admin:kyverno-platform
